Repository Nexters/kekeche-be, pull requests merged in 2024-02, with the labels that each got.

#40 [FEAT] 해시태그 저장 및 기록 수정
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/nexters/kekechebe/domain/hashtag/entity/Hashtag.java
  src/main/java/com/nexters/kekechebe/domain/hashtag/repository/HashtagRepository.java
  src/main/java/com/nexters/kekechebe/domain/memo/controller/MemoController.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/CharacterDetail.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/request/MemoCreateRequest.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/request/MemoUpdateRequest.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/response/MemoDetail.java
  src/main/java/com/nexters/kekechebe/domain/memo/entity/Memo.java
  src/main/java/com/nexters/kekechebe/domain/memo/repository/MemoRepository.java
  src/main/java/com/nexters/kekechebe/domain/memo/service/MemoService.java
  src/main/java/com/nexters/kekechebe/domain/memo_hashtag/entity/MemoHashtag.java
Labels: ✨ FEAT

#41 [FEAT] 캐릭터 기능 구현
  src/main/java/com/nexters/kekechebe/domain/character/controller/CharacterController.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/request/CharacterCreateRequest.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/request/CharacterNameUpdateRequest.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterIdResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterListResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/entity/Character.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/CharacterAsset.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/Item.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/Keyword.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/Level.java
  src/main/java/com/nexters/kekechebe/domain/character/repository/CharacterRepository.java
  src/main/java/com/nexters/kekechebe/domain/character/service/CharacterService.java
  src/main/java/com/nexters/kekechebe/domain/member/controller/MemberController.java
  src/main/java/com/nexters/kekechebe/domain/member/service/MemberService.java
Labels: ✨ FEAT

#44 [FIX] 캐릭터 수정
  build.gradle
  src/main/java/com/nexters/kekechebe/domain/auth/controller/AuthController.java
  src/main/java/com/nexters/kekechebe/domain/character/controller/CharacterController.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/request/CharacterCreateRequest.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/entity/Character.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/CharacterAsset.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/Keyword.java
  src/main/java/com/nexters/kekechebe/domain/character/service/CharacterService.java
  src/main/java/com/nexters/kekechebe/domain/member/controller/MemberController.java
Labels: 🐞 FIX

#45 [FEAT] 캐릭터 레벨업 외
  src/main/java/com/nexters/kekechebe/config/SecurityConfig.java
  src/main/java/com/nexters/kekechebe/domain/character/controller/CharacterController.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterIdResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterLevelUpResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterThumbnailResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/entity/Character.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/CharacterAsset.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/Item.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/Level.java
  src/main/java/com/nexters/kekechebe/domain/character/service/CharacterService.java
  src/main/java/com/nexters/kekechebe/domain/memo/controller/MemoController.java
  src/main/java/com/nexters/kekechebe/domain/memo/service/MemoService.java
  src/main/java/com/nexters/kekechebe/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nexters/kekechebe/jwt/JwtUtil.java
  src/main/java/com/nexters/kekechebe/util/UrlMaker.java
Labels: 🐞 FIX, ✨ FEAT, ✔CHORE

#46 [FEAT] 캐릭터 생성 후 로그인 기능 구현
  src/main/java/com/nexters/kekechebe/domain/auth/controller/AuthController.java
  src/main/java/com/nexters/kekechebe/domain/auth/service/AuthService.java
Labels: ✨ FEAT

#47 [CHORE] 최상위 Exception 핸들링 추가
  src/main/java/com/nexters/kekechebe/exceptions/GlobalExceptionHandler.java
Labels: ✔CHORE

#48 [FEAT] 회원 조회, 캐릭터 전체 조회 api에 member nickname 추가
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterListResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/service/CharacterService.java
  src/main/java/com/nexters/kekechebe/domain/member/dto/response/MemberResponse.java
  src/main/java/com/nexters/kekechebe/domain/member/service/MemberService.java
Labels: ✨ FEAT

#49 [FIX] 캐릭터 생성 후 로그인 security config 추가
  src/main/java/com/nexters/kekechebe/config/SecurityConfig.java
Labels: 🐞 FIX

#50 [FIX] 메모 엔티티 html content 추가
  src/main/java/com/nexters/kekechebe/domain/memo/dto/request/MemoCreateRequest.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/request/MemoUpdateRequest.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/response/MemoDetail.java
  src/main/java/com/nexters/kekechebe/domain/memo/entity/Memo.java
  src/main/java/com/nexters/kekechebe/domain/memo/service/MemoService.java
Labels: 🐞 FIX

#51 [FIX] 메모 저장 시 htmlContent도 저장하도록 변경
  src/main/java/com/nexters/kekechebe/domain/memo/entity/Memo.java
  src/main/java/com/nexters/kekechebe/domain/memo/service/MemoService.java
Labels: 🐞 FIX

#52 [CHORE] 컨테이너 시간 설정을 위한 Dockerfile 수정
  Dockerfile
Labels: 📝 DOCS

#53 Refactor/member
  src/main/java/com/nexters/kekechebe/domain/auth/client/kakao/KakaoAuthClient.java
  src/main/java/com/nexters/kekechebe/domain/auth/controller/AuthController.java
  src/main/java/com/nexters/kekechebe/domain/auth/service/AuthService.java
  src/main/java/com/nexters/kekechebe/domain/auth/service/KakaoAuthService.java
  src/main/java/com/nexters/kekechebe/domain/member/controller/MemberController.java
  src/main/java/com/nexters/kekechebe/domain/member/service/MemberService.java
Labels: ♻ REFACTOR

#54 [REFACTOR] 캐릭터 관련 로직 분리
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterLevelUpResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/entity/Character.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/CharacterAsset.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/Level.java
  src/main/java/com/nexters/kekechebe/domain/memo/service/CharacterHelperService.java
  src/main/java/com/nexters/kekechebe/domain/memo/service/MemoService.java
  src/main/java/com/nexters/kekechebe/util/character/LevelUtil.java
Labels: ✨ FEAT, ♻ REFACTOR

#55 [REFACTOR] 캐릭터 코드 리팩토링
  src/main/java/com/nexters/kekechebe/domain/character/dto/request/CharacterCreateRequest.java
  src/main/java/com/nexters/kekechebe/domain/character/entity/Character.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/CharacterAsset.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/Item.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/Keyword.java
  src/main/java/com/nexters/kekechebe/domain/character/service/CharacterService.java
  src/main/java/com/nexters/kekechebe/util/UrlMaker.java
  src/main/java/com/nexters/kekechebe/util/character/LevelUtil.java
Labels: ♻ REFACTOR

#56 [FIX] 카카오 로그인 시 트랜잭션 수정 및 CORS 도메인 추가
  src/main/java/com/nexters/kekechebe/config/SecurityConfig.java
  src/main/java/com/nexters/kekechebe/domain/auth/service/KakaoAuthService.java
Labels: 🐞 FIX

#57 [FEAT] Character Validation 추가
  build.gradle
  src/main/java/com/nexters/kekechebe/domain/character/controller/CharacterController.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/request/CharacterCreateRequest.java
  src/main/java/com/nexters/kekechebe/domain/character/enums/CharacterAsset.java
  src/main/java/com/nexters/kekechebe/util/UrlMaker.java
Labels: ✨ FEAT, ♻ REFACTOR

#58 [Feat] 주특기 기능 구현 (저장, 삭제)
  src/main/java/com/nexters/kekechebe/domain/character/controller/CharacterController.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/request/SpecialtyCreateRequest.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/request/SpecialtyInfo.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/SpecialtyDetail.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/SpecialtyResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/service/CharacterService.java
  src/main/java/com/nexters/kekechebe/domain/specialty/entity/Specialty.java
  src/main/java/com/nexters/kekechebe/domain/specialty/repository/SpecialtyRepository.java
Labels: ✨ FEAT

#59 [REFACOTR] 이미지 확장자 변경 및 item 이미지 null 처리
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterLevelUpResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterResponse.java
  src/main/java/com/nexters/kekechebe/util/UrlMaker.java
Labels: ♻ REFACTOR

#60 [REFACTOR] Set-Cookie 테스트 적용
  src/main/java/com/nexters/kekechebe/domain/auth/controller/AuthController.java
Labels: ♻ REFACTOR

#61 [FEAT] 응원하기 기능 구현
  src/main/java/com/nexters/kekechebe/config/SecurityConfig.java
  src/main/java/com/nexters/kekechebe/domain/character/service/CharacterService.java
  src/main/java/com/nexters/kekechebe/domain/member/controller/MemberController.java
  src/main/java/com/nexters/kekechebe/domain/member/dto/response/MemberCheerResponse.java
  src/main/java/com/nexters/kekechebe/domain/member/entity/Member.java
  src/main/java/com/nexters/kekechebe/domain/member/service/MemberService.java
  src/main/java/com/nexters/kekechebe/exceptions/StatusCode.java
Labels: ✨ FEAT

#62 [FIX] 주특기 기획에 따른 기록 로직 수정
  src/main/java/com/nexters/kekechebe/domain/character/repository/CharacterRepository.java
  src/main/java/com/nexters/kekechebe/domain/hashtag/repository/HashtagRepository.java
  src/main/java/com/nexters/kekechebe/domain/member/controller/MemberController.java
  src/main/java/com/nexters/kekechebe/domain/member/service/MemberService.java
  src/main/java/com/nexters/kekechebe/domain/memo/controller/MemoController.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/request/MemoCreateRequest.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/request/MemoUpdateRequest.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/response/MemoDetail.java
  src/main/java/com/nexters/kekechebe/domain/memo/entity/Memo.java
  src/main/java/com/nexters/kekechebe/domain/memo/repository/MemoRepository.java
  src/main/java/com/nexters/kekechebe/domain/memo/service/MemoService.java
  src/main/java/com/nexters/kekechebe/domain/memo_specialty/entity/MemoSpecialty.java
  src/main/java/com/nexters/kekechebe/domain/memo_specialty/repository/MemoSpecialtyRepository.java
  src/main/java/com/nexters/kekechebe/domain/specialty/entity/Specialty.java
  src/main/java/com/nexters/kekechebe/domain/specialty/repository/SpecialtyRepository.java
  src/main/java/com/nexters/kekechebe/util/specialty/SpecialtyUtil.java
  src/test/java/com/nexters/kekechebe/SpecialtyUtilTest.java
Labels: 🐞 FIX, ✨ FEAT

#63 [FEAT] 주특기 조회 기능 구현
  src/main/java/com/nexters/kekechebe/domain/character/controller/CharacterController.java
  src/main/java/com/nexters/kekechebe/domain/character/service/CharacterService.java
  src/main/java/com/nexters/kekechebe/domain/memo/controller/MemoController.java
  src/main/java/com/nexters/kekechebe/domain/specialty/repository/SpecialtyRepository.java
Labels: ✨ FEAT

#64 [FEAT] 캐릭터 전체 조회 시, response에 응원하기 카운트 추가
  src/main/java/com/nexters/kekechebe/domain/character/dto/response/CharacterListResponse.java
  src/main/java/com/nexters/kekechebe/domain/character/service/CharacterService.java
Labels: ✨ FEAT

#65 [FIX] @Param 추가
  src/main/java/com/nexters/kekechebe/domain/memo/repository/MemoRepository.java
Labels: 🐞 FIX
