Repository Nexters/kekeche-be, pull requests merged in 2024-01, with the labels that each got.

#20 [FEAT] Base Response 설정
  src/main/java/com/nexters/kekechebe/dto/BaseResponse.java
  src/main/java/com/nexters/kekechebe/dto/DataResponse.java
Labels: FEAT

#19 [FEAT] Exception 설정
  src/main/java/com/nexters/kekechebe/exceptions/CustomException.java
  src/main/java/com/nexters/kekechebe/exceptions/ExceptionResponse.java
  src/main/java/com/nexters/kekechebe/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nexters/kekechebe/exceptions/StatusCode.java
Labels: FEAT

#22 [FEAT] Timestamped 생성
  src/main/java/com/nexters/kekechebe/KekecheBeApplication.java
  src/main/java/com/nexters/kekechebe/util/Timestamped.java
Labels: FEAT

#25 [CHORE] Ignore 설정
  .gitignore
  src/main/resources/application.properties
Labels: CHORE

#26 [FEAT] 엔티티 생성 #23
  src/main/java/com/nexters/kekechebe/domain/character/entity/Character.java
  src/main/java/com/nexters/kekechebe/domain/hashtag/entity/Hashtag.java
  src/main/java/com/nexters/kekechebe/domain/member/entity/Member.java
  src/main/java/com/nexters/kekechebe/domain/memo/entity/Memo.java
  src/main/java/com/nexters/kekechebe/domain/memo_hashtag/entity/MemoHashtag.java
Labels: FEAT

#29 [FIX] Mysql 예약어로 인한 Character entity 수정
  src/main/java/com/nexters/kekechebe/domain/character/entity/Character.java
Labels: FIX

#30 [FEAT] 기록 기능 구현
  src/main/java/com/nexters/kekechebe/domain/character/repository/CharacterRepository.java
  src/main/java/com/nexters/kekechebe/domain/member/repository/MemberRepository.java
  src/main/java/com/nexters/kekechebe/domain/memo/controller/MemoController.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/request/MemoCreateRequest.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/request/MemoUpdateRequest.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/response/MemoDetail.java
  src/main/java/com/nexters/kekechebe/domain/memo/dto/response/MemoPage.java
  src/main/java/com/nexters/kekechebe/domain/memo/entity/Memo.java
  src/main/java/com/nexters/kekechebe/domain/memo/repository/MemoRepository.java
  src/main/java/com/nexters/kekechebe/domain/memo/service/MemoService.java
  src/main/java/com/nexters/kekechebe/domain/memo_hashtag/entity/MemoHashtag.java
  src/main/java/com/nexters/kekechebe/exceptions/StatusCode.java
Labels: FEAT

#31 [FEAT] 하루 기준 기록 초과 작성 시 반려 처리
  src/main/java/com/nexters/kekechebe/domain/memo/repository/MemoRepository.java
  src/main/java/com/nexters/kekechebe/domain/memo/service/MemoService.java
  src/main/java/com/nexters/kekechebe/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nexters/kekechebe/util/time/TimeUtil.java
  src/main/java/com/nexters/kekechebe/util/time/Today.java
  src/test/java/com/nexters/kekechebe/TimeUtilTest.java
Labels: FEAT

#32 [FEAT] 카카오 소셜 로그인 구현
  build.gradle
  src/main/java/com/nexters/kekechebe/config/SecurityConfig.java
  src/main/java/com/nexters/kekechebe/domain/auth/controller/AuthController.java
  src/main/java/com/nexters/kekechebe/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/nexters/kekechebe/domain/auth/dto/response/TokenResponse.java
  src/main/java/com/nexters/kekechebe/domain/auth/dto/response/UserInfoResponse.java
  src/main/java/com/nexters/kekechebe/domain/auth/service/AuthService.java
  src/main/java/com/nexters/kekechebe/domain/member/entity/Member.java
  src/main/java/com/nexters/kekechebe/domain/member/repository/MemberRepository.java
  src/main/java/com/nexters/kekechebe/exceptions/StatusCode.java
  src/main/java/com/nexters/kekechebe/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/nexters/kekechebe/jwt/JwtAuthFilter.java
  src/main/java/com/nexters/kekechebe/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/nexters/kekechebe/jwt/JwtUtil.java
  src/main/java/com/nexters/kekechebe/security/UserDetailsImpl.java
  src/main/java/com/nexters/kekechebe/security/UserDetailsServiceImpl.java
Labels: ✨ FEAT

#35 [DOCS] 기록 도메인 swagger 추가
  build.gradle
  src/main/java/com/nexters/kekechebe/config/SecurityConfig.java
  src/main/java/com/nexters/kekechebe/domain/memo/controller/MemoController.java
Labels: 📝 DOCS

#37 [FIX] 소셜 로그인 버그 수정
  src/main/java/com/nexters/kekechebe/config/SecurityConfig.java
  src/main/java/com/nexters/kekechebe/domain/auth/controller/AuthController.java
  src/main/java/com/nexters/kekechebe/domain/auth/dto/response/TokenResponse.java
  src/main/java/com/nexters/kekechebe/domain/auth/service/AuthService.java
Labels: 🐞 FIX
